### ISSUE TITLE
Determine what plots you will make, and render them

### ISSUE THREAD

**Issue by VCF** [cherrypi/Science-Fair_2019#12]
Once you think you have a handle on `ggplot2`, you need to determine what scatter plots you want to make to present your data.

* Think about how many plots you want; Don't overdo it
* Generate the plots "on screen" first to inspect them, then save them as `.png` files

**Comment by cherrypi** [comment]
What do you mean by "on screen"?

**Comment by cherrypi** [comment]
I get this error message when I run my graph in R:
`Warning messages:
1: Removed 57 rows containing non-finite values (stat_smooth). 
2: Removed 57 rows containing missing values (geom_point). 
`

**Comment by VCF** [comment]
Your plots in 9f976f5 look great! You've done a good job learning the weird `+` notation that ggplot uses.
