### ISSUE TITLE
Take out snow measurements in the $Rain column

### ISSUE THREAD

**Issue by VCF** [cherrypi/Science-Fair_2019#15]
You've mixed in snow depth in the same column as `$Rain`. This isn't good; 1 inch of snow is less - generally much less - than an inch of rain. You have 6.5" as your maximum "rainfall", due to a day when we got six and a half inches of snow - that's an apocalyptic rainfall, and would involve the National Guard, FEMA and probably most religious leaders in the state.

**Comment by VCF** [comment]
I see in 9f976f5 you `NA`ed out the 6.5" measurement. Was that the only snow measurement in your rainfall? I presumed you had more snowfall recordings this last winter.

**Comment by cherrypi** [comment]
Actually yes, it was the only one I recorded.

**Comment by VCF** [comment]
Very well, closing.
