### ISSUE TITLE
Mangled data frame - misquoted CSV

### ISSUE THREAD

**Issue by VCF** [cherrypi/Science-Fair_2019#5]
Your data frame has columns thrown into inappropriate places, and is emitting the error "EOF within quoted string". I looked at the file and you're not properly closing your quotes in all places. Double check the  file and make sure that for any value that you start a quote that you also end it (or any value ending with a quote is also starting with one).

**Comment by cherrypi** [comment]
I fixed the quotes in c0465de, but it still seemed broken when I checked it with str(), I can only think that maybe I'm using invalid characters or it doesn't agree with the fact that some columns have data in it that is sometimes only numbers and other times numbers and letters.

**Comment by VCF** [comment]
No, I think you've dealt with the immediate problem! I know what the next one is, I'll clue you in with the next issue.
